spring.application.name=commitment

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.flyway.enabled=false
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}
